enabled: true

keycloak:
  keycloak:
    image:
      tag: 9.0.3 # keycloak controller does not support 10.x yet
    extraInitContainers: |
      - name: theme-provider
        image: gcr.io/cldntventr/keycloak-theme:0.0.32
        imagePullPolicy: IfNotPresent
        command:
          - sh
        args:
          - -c
          - |
            echo "Copying theme..."
            cp -R /logo/* /theme
        volumeMounts:
          - name: theme
            mountPath: /theme
    extraVolumeMounts: |
      - name: theme
        mountPath: /opt/jboss/keycloak/themes/logo
    extraVolumes: |
      - name: theme
        emptyDir: {}
    persistence:
      dbVendor: postgres
    resources:
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi
    service:
      annotations:
        fabric8.io/expose: "true"
        fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
        fabric8.io/ingress.name: "auth"

postgresql-ha:
  metrics:
    enabled: true
  networkPolicy:
    enabled: true
    allowExternal: false
  postgresql:
    affinity: |
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app.kubernetes.io/component"
                  operator: In
                  values:
                    - postgresql
            topologyKey: kubernetes.io/hostname
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app.kubernetes.io/component"
                    operator: In
                    values:
                      - postgresql
              topologyKey: failure-domain.beta.kubernetes.io/zone
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi
  pgpool:
    affinity: |
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app.kubernetes.io/component"
                  operator: In
                  values:
                    - pgpool
            topologyKey: kubernetes.io/hostname
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app.kubernetes.io/component"
                    operator: In
                    values:
                      - pgpool
              topologyKey: failure-domain.beta.kubernetes.io/zone
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi

postgresAdminPassword:
postgresAdminUsername:
keycloakAdminPassword:
keycloakAdminUsername:

keycloak-controller:
  enabled: true
  namespaced: false
  javaToolOptions: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=50.0"
  resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi

realms:
  dev: dev-staging
  members: members-staging