keycloak:
  keycloak:
    persistence:
      dbVendor: 'postgres'
      deployPostgres: true
    service:
      annotations:
        fabric8.io/expose: "true"
        fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
