keycloak:
  keycloak:
    persistence:
      dbVendor: 'postgres'
    service:
      annotations:
        fabric8.io/expose: "true"
        fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
postgres-ha:
  metrics:
    enabled: true
  networkPolicy:
    enabled: true
    allowExternal: false

postgresAdminPassword:
postgresAdminUsername:
keycloakAdminPassword:
keycloakAdminUsername: