enabled: true

keycloak:
  keycloak:
    image:
      tag: 9.0.3 # keycloak controller does not support 10.x yet
    extraInitContainers: |
      - name: theme-provider
        image: gcr.io/cldntventr/keycloak-theme:0.0.32
        imagePullPolicy: IfNotPresent
        command:
          - sh
        args:
          - -c
          - |
            echo "Copying theme..."
            cp -R /logo/* /theme
        volumeMounts:
          - name: theme
            mountPath: /theme
    extraVolumeMounts: |
      - name: theme
        mountPath: /opt/jboss/keycloak/themes/logo
    extraVolumes: |
      - name: theme
        emptyDir: {}
    persistence:
      deployPostgres: false
    resources:
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi
    service:
      annotations:
        fabric8.io/expose: "true"
        fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
        fabric8.io/ingress.name: "auth"

keycloakAdminPassword:
keycloakAdminUsername:

realms:
  dev: dev-staging
  members: members-staging