keycloak:
  keycloak:
    extraArgs: -Dkeycloak.profile.feature.scripts=enabled
    extraInitContainers: |
      - name: theme-provider
        image: gcr.io/cldntventr/keycloak-theme:0.0.32
        imagePullPolicy: IfNotPresent
        command:
          - sh
        args:
          - -c
          - |
            echo "Copying theme..."
            cp -R /logo/* /theme
        volumeMounts:
          - name: theme
            mountPath: /theme
    extraVolumeMounts: |
      - name: theme
        mountPath: /opt/jboss/keycloak/themes/logo
    extraVolumes: |
      - name: theme
        emptyDir: {}
    persistence:
      dbVendor: postgres
    resources:
      limits:
        cpu: 100m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi
    service:
      annotations:
        fabric8.io/expose: "true"
        fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
postgres-ha:
  metrics:
    enabled: true
  networkPolicy:
    enabled: true
    allowExternal: false

postgresAdminPassword:
postgresAdminUsername:
keycloakAdminPassword:
keycloakAdminUsername:

keycloak-controller:
  namespaced: false