enabled: true

keycloak:
  keycloak:
    extraInitContainers: |
      - name: theme-provider
        image: gcr.io/cldntventr/keycloak-theme:0.0.32
        imagePullPolicy: IfNotPresent
        command:
          - sh
        args:
          - -c
          - |
            echo "Copying theme..."
            cp -R /logo/* /theme
        volumeMounts:
          - name: theme
            mountPath: /theme
    extraVolumeMounts: |
      - name: theme
        mountPath: /opt/jboss/keycloak/themes/logo
    extraVolumes: |
      - name: theme
        emptyDir: {}
    persistence:
      dbVendor: postgres
    resources:
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi
    service:
      annotations:
        fabric8.io/expose: "true"
        fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
        fabric8.io/ingress.name: "auth"

postgresql-ha:
  persistence:
    storageClass: ssd
    size: 100Gi
  metrics:
    enabled: true
  networkPolicy:
    enabled: true
    allowExternal: false
  postgresql:
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi
  pgpool:
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi

postgresAdminPassword:
postgresAdminUsername:
keycloakAdminPassword:
keycloakAdminUsername:

keycloak-controller:
  namespaced: false
  javaToolOptions: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=50.0"
  resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 256Mi