keycloak:
  keycloak:
    persistence:
      dbVendor: 'postgres'
      dbHost: jx-postgresql-ha-postgresql.{{ .Release.Namespace }}.svc.cluster.local
    service:
      annotations:
        fabric8.io/expose: "true"
        fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"

postgresAdminPassword:
postgresAdminUsername:
keycloakAdminPassword:
keycloakAdminUsername: