apiVersion: k8s.kiwigrid.com/v1beta1
kind: KeycloakClient
metadata:
  name: sso
spec:
  keycloak: sso
  realm: sso
  clientId: sso
  clientType: public
  directAccessGrantsEnabled: true
  standardFlowEnabled: false
  implicitFlowEnabled: false
  mapper:
  - name: sso-audience
    protocolMapper: oidc-audience-mapper
    config:
      claim.name: audience
      access.token.claim: "true"
      included.client.audience: sso