apiVersion: v1
kind: Secret
metadata:
  name: auth-keycloak
stringData:
  password: {{ required "keycloakAdminPassword is required." .Values.keycloakAdminPassword }}
  user: {{ required "keycloakAdminUser is required." .Values.keycloakAdminUser }}
type: Opaque
