{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: auth-keycloak
stringData:
  adminPassword: {{ required "keycloakAdminPassword is required." .Values.keycloakAdminPassword }}
  adminUsername: {{ required "keycloakAdminUsername is required." .Values.keycloakAdminUsername }}
type: Opaque
{{- end }}
