apiVersion: v1
kind: Secret
metadata:
  name: auth-postgres
stringData:
  password: {{ required "postgresAdminPassword is required." .Values.postgresAdminPassword }}
  user: {{ required "postgresAdminUser is required." .Values.postgresAdminPassword }}
type: Opaque
