{{- if .Values.enabled }}
apiVersion: k8s.kiwigrid.com/v1beta1
kind: KeycloakRealm
metadata:
  name: {{ .Values.realms.members }}
spec:
  keycloak: keycloak-{{ .Release.Namespace }}
  realm: {{ .Values.realms.members }}
  roles:
  - admin
  - member
  - service
  - gdd
  - db
  - fcf
  - fsf
  - md
  - lp
{{- end }}